packages:
  - packages/*

allowScripts: better-sqlite3

ignoredBuiltDependencies:
  - better-sqlite3

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - electron
  - electron-winstaller
  - esbuild
  - sharp
  - unrs-resolver
