packages:
  - packages/*

allowScripts: better-sqlite3

ignoredBuiltDependencies:
  - better-sqlite3

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - electron
  - esbuild
  - sharp
  - unrs-resolver
