import * as esbuild from "esbuild";

await esbuild.build({
  entryPoints: ["src/index.ts"],
  bundle: true,
  platform: "node",
  format: "cjs",
  outfile: "dist/bundle.cjs",
  external: [],
  minify: false,
  sourcemap: false,
  target: "node20",
  banner: {
    js: "// WeebCentral Extension Bundle - Generated by esbuild",
  },
  footer: {
    // Fix for ESM import compatibility
    js: `
// When using ESM import() on a CJS module, Node wraps module.exports in a 'default' property.
// So if module.exports = { default: extension }, ESM sees { default: { default: extension } }.
// The extension loader checks imported.default for the extension, so we need:
// - module.exports = extension (so ESM import sees { default: extension })
if (module.exports && module.exports.default) {
  module.exports = module.exports.default;
}
`,
  },
  // Properly handle Node.js built-ins
  mainFields: ["module", "main"],
  conditions: ["node"],
});

console.log("✓ Bundle created at dist/bundle.cjs");
