import * as esbuild from "esbuild";

await esbuild.build({
  entryPoints: ["dist/index.js"],
  bundle: true,
  platform: "node",
  format: "cjs",
  outfile: "dist/bundle.cjs",
  external: [],
  minify: false,
  sourcemap: false,
  target: "node20",
  banner: {
    js: "// WeebCentral Extension Bundle - Generated by esbuild",
  },
  // Properly handle Node.js built-ins
  mainFields: ["module", "main"],
  conditions: ["node"],
});

console.log("✓ Bundle created at dist/bundle.cjs");
